### ISSUE TITLE
If you scroll up mobile you can see the roll

### ISSUE THREAD

**Issue by ghost** [sorenrehkopf/custom-rick-roll#33] opened 2021-10-09 14:51 UTC

**Comment by superintendent2521** [comment] 2021-11-10 13:13
A way to fix this is  by making the Accept cookies and Roll two diffrent pages,

**Comment by sorenrehkopf** [comment] 2022-01-12 01:32
I am unable to reproduce on my own devices. If you're able to repro reliably on your device feel free to open a pr with a fix! I'm going to close this for now though. I can reopen if it seems to be a widespread issue.

**Closed as completed by sorenrehkopf** 2022-01-12 01:32 UTC
