### ISSUE TITLE
I Managed to Get controls

### ISSUE THREAD

**Issue by Emma-coder67** [sorenrehkopf/custom-rick-roll#29] opened 2021-07-02 14:21 UTC
![image](https://user-images.githubusercontent.com/83362361/124288373-bbe27c80-db6e-11eb-8cac-637757f52b6e.png)

**Comment by zaourzag** [comment] 2021-07-05 06:08
https://github.com/sorenrehkopf/custom-rick-roll/issues/26#issuecomment-871163796 look at this

**Comment by pratyaksh123** [comment] 2021-07-16 12:20
Just delete the iFrame node from the DOM . LOL

**Comment by WGrav01** [comment] 2021-08-11 16:02
This is because you can click the pause/play button on the keyboard to pause the video. Not sure how to fix.

**Comment by sorenrehkopf** [comment] 2022-01-12 01:25
This is a duplicate of https://github.com/sorenrehkopf/custom-rick-roll/issues/26. See comments there for clarification.

**Closed as completed by sorenrehkopf** 2022-01-12 01:25 UTC
