### ISSUE TITLE
Wrong url

### ISSUE THREAD

**Issue by Mineboi** [sorenrehkopf/custom-rick-roll#24] opened 2021-02-26 16:48 UTC
The link said free robux

**Comment by ghost** [comment] 2021-03-12 19:33
?

**Comment by JohnB17** [comment] 2021-03-26 00:58
I think they mean they made a link for something, but it said free robux instead of what they chose.
Or, they got trolled.

**Comment by Rexogamer** [comment] 2021-03-27 12:01
...they got trolled :p

**Comment by sorenrehkopf** [comment] 2021-03-28 03:36
Sorry it's taken me so long to reply to this, I was confused about what the issue was here, but I believe the comments above are probably correct, and we may have found the remaining person on the internet who doesn't know what rick rolling is. 🎉 🌟

This is a monumentous discovery and I'm so proud to have taken part. 

For @Mineboi, I believe the page was working as intended so I'm gonna close this. 

Here's a helpful article to explain. https://www.sanfransentinel.com/a-brief-history-of-rick-rolling.html

**Closed as completed by sorenrehkopf** 2021-03-28 03:36 UTC

**Comment by ghost** [comment] 2021-03-28 14:37
You got me :P
